### PR TITLE
Add position property

### PR DESCRIPTION
**Pull request by enghelewa**
Add `position` property to be passed to `v-dropdown` component. This is helpful for `RTL` languages

### CODE REVIEW

**Comment by TerryZ** [comment]
The `position` option for `v-dropdown` is config drop down container align which side to caller, not for inner content.

**Comment by enghelewa** [comment]
@TerryZ  Yes but it will be very helpful for people working in RTL interfaces

**Comment by enghelewa** [comment]
If you could add a class to indicate RTL when using the `:rtl="true"` property you are intending to add, This will be very good to start with for RTL interfaces. 

And using the class you will add it will become easy to manipulate the HTML of the different parts of the component

sketch

**Comment by TerryZ** [comment]
Has been add `rtl` option to set RTL interface, this PR will close.

**Pull request closed without merging**
